### DOCKER_VERSIONS ###########################################################

# Docker image versions
DOCKER_VERSIONS		?= 3.9

### MK_DOCKER_IMAGE ############################################################

PROJECT_DIR		?= $(abspath ..)
include $(PROJECT_DIR)/docker.variant.mk

################################################################################
