###
### Default configuration
###

version: "3.3"

networks:
  default:

services:
  baseimage:
    image: ${DOCKER_IMAGE}
    depends_on:
      - simple_ca
    environment:
      - DOCKER_ENTRYPOINT_INFO=true
      - SERVER_CRT_HOST=baseimage.local
      - SERVER_P12_FILE=${SERVER_P12_FILE:-/etc/ssl/private/server.p12}
      - SIMPLE_CA_URL=https://simple-ca.local
    networks:
      default:
        aliases:
          - baseimage.local
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CURDIR}/secrets/ca_crt.pem:${CA_CRT_FILE:-/etc/ssl/certs/ca_crt.pem}:ro
      - ${CURDIR}/secrets/ca_user.name:${CA_USER_NAME_FILE:-/etc/ssl/private/ca_user.name}:ro
      - ${CURDIR}/secrets/ca_user.pwd:${CA_USER_PWD_FILE:-/etc/ssl/private/ca_user.pwd}:ro
      - ${CURDIR}/secrets/server_key.pwd:${SERVER_KEY_PWD_FILE:-/etc/ssl/private/server_key.pwd}:ro

  simple_ca:
    image: ${SIMPLE_CA_IMAGE}
    environment:
      - DOCKER_ENTRYPOINT_INFO=true
      - SERVER_CRT_HOST=simple-ca.local
    networks:
      default:
        aliases:
          - simple-ca.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${SECRETS_DIR}/secrets:/var/lib/simple-ca/secrets

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD:-rspec}
    depends_on:
      - baseimage
    env_file:
      - ${TEST_ENV_FILE}
    networks:
      default:
        aliases:
          - test.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TEST_PROJECT_VOLUME:-project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

volumes:
  project_dir:
