###
### Default configuration
###

version: "3.3"

networks:
  default:

services:
  baseimage:
    image: ${DOCKER_IMAGE}
    # Listen on TCP port 7 (Echo Protocol) and mirror input to output
    command: /usr/bin/ncat -l 7 -k -c /bin/cat
    depends_on:
      - simple_ca
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - SERVER_CRT_HOST=${SERVER_CRT_HOST}
      - SERVER_KEY_PWD_FILE=${SERVER_KEY_PWD_FILE}
      - SERVER_P12_FILE=${SERVER_P12_FILE}
      - SIMPLE_CA_URL=https://simple-ca.local
    expose:
      - 7/tcp
    networks:
      default:
        aliases:
          - baseimage.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  simple_ca:
    image: ${SIMPLE_CA_IMAGE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - SERVER_CRT_HOST=simple-ca.local
    networks:
      default:
        aliases:
          - simple-ca.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_data:/var/lib/simple-ca
      - simple_ca_secrets:/var/lib/simple-ca/secrets

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - baseimage
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      # Wait untill the tested container is started
      - WAIT_FOR_TCP=baseimage.local:7
    networks:
      default:
        aliases:
          - test.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - simple_ca
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      # Wait until the tested container is started
      - WAIT_FOR_TCP=baseimage.local:7
      - WAIT_FOR_TIMEOUT=5
    networks:
      default:
        aliases:
          - wait.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets:ro

volumes:
  test_project_dir:
  simple_ca_data:
  simple_ca_secrets:
