version: 2
jobs:
  build:
    docker:
      - image: sicz/dockerspec@sha256:6b84ce81f01e2e25e01483ce4aff1a3c996b4f775dbaa0a7d7f1589d52b69690
    environment:
      - MAKEFLAGS=--no-print-directory
      - DOCKER_TEST_IMAGE=
    steps:
      - checkout
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Remote Docker engine version
          command: |
            docker version
      - run:
          name: Build and test latest Alpine Linux image
          command: |
            make all
      - run:
          name: Build and test development Alpine Linux image
          working_directory: devel
          command: |
            make all
      - run:
          name: Build and test latest Dockerspec image
          working_directory: dockerspec
          command: |
            make all
      - run:
          name: Build and test development Dockerspec image
          working_directory: dockerspec/devel
          command: |
            make all
      - run:
          name: Build and test latest CentOS image
          working_directory: centos
          command: |
            make all
      - run:
          name: Build and test development CentOS image
          working_directory: centos/devel
          command: |
            make all
      - deploy:
          name: Push latest Alpine Linux image to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
      - deploy:
          name: Push development Alpine Linux image to Docker Hub
          working_directory: devel
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
      - deploy:
          name: Push latest Dockerspec image to Docker Hub
          working_directory: dockerspec
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
      - deploy:
          name: Push development Dockerspec image to Docker Hub
          working_directory: dockerspec/devel
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
      - deploy:
          name: Push latest CentOS image to Docker Hub
          working_directory: centos
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
      - deploy:
          name: Push development CentOS image to Docker Hub
          working_directory: centos/devel
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
