version: 2

jobs:

  # Build image macro
  build_image: &build_image
    # docker:
    #   - image: sicz/dockerspec:3.6
    machine: true
    working_directory: ~/docker-baseimage
    environment:
      - MAKEFLAGS=--no-print-directory
    steps:
      - run:
          name: Upgrade Docker Engine
          command: |
            docker version
            curl -fsSL https://raw.githubusercontent.com/StefanScherer/docker-init/master/ubuntu/install-docker-ce.sh | sh
      - run:
          name: Set up Environment
          command: |
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master ~/Mk
      - checkout
      # - setup_remote_docker
      - run:
          name: Docker Engine version
          command: |
            docker version
      - run:
          name: Build Docker image
          command: |
            cd ${CIRCLE_STAGE}
            make rebuild
      - run:
          name: Run Docker container
          command: |
            cd ${CIRCLE_STAGE}
            make run
            make logs
      # - run:
      #     name: Run tests
      #     command: |
      #       cd ${CIRCLE_STAGE}
      #       ln -s ../.rspec .rspec
      #       ln -s ../spec spec
      #       env DOCKER_CONTAINER_ID=$(cat .container_id) rspec --format doc
      - run:
          name: Run tests
          command: |
            cd ${CIRCLE_STAGE}
            make test DOCKER_TEST_CMD="--format doc"

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi

  alpine/3.6:
    <<: *build_image
  centos/7:
    <<: *build_image

workflows:
  version: 2
  build:
    jobs:
      - alpine/3.6
      - centos/7
