version: 2
jobs:
  build:
    docker:
      - image: sicz/dockerspec@sha256:5f1324c5ec967301a4cb764d3e97a90605281fe38a7c94ec3e9b09d3354cbd30
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Remote Docker engine version and images
          command: |
            docker --version
            docker-compose --version
            docker image ls
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - run:
          name: sicz/baseimage-alpine:latest
          working_directory: alpine
          command: |
            make ci
      - run:
          name: sicz/baseimage-alpine:devel
          working_directory: alpine/devel
          command: |
            make ci
      - run:
          name: sicz/baseimage-centos:latest
          working_directory: centos
          command: |
            make ci
      - run:
          name: sicz/baseimage-centos:devel
          working_directory: centos/devel
          command: |
            make ci
      - deploy:
          name: Push images to the Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push-all
            fi
