version: 2
jobs:
  build: &build
    docker:
      - image: sicz/dockerspec
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - run:
          name: Build and test Docker image
          command: |
            cd ${BUILD_DIR}
            make ci
      - run:
          name: Save Docker image to workspace
          command: |
            cd ${BUILD_DIR}
            mkdir -p /tmp/workspace
            make docker-save-image DOCKER_IMAGE_DEPOT=/tmp/workspace
            ls -lh /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*.image"

  alpine-3.6:
    <<: *build
    environment:
      - BUILD_DIR=alpine/3.6
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  alpine-edge:
    <<: *build
    environment:
      - BUILD_DIR=alpine/edge
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  centos-7:
    <<: *build
    environment:
      - BUILD_DIR=centos/7
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  publish:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - attach_workspace:
          at: /tmp/workspace
      - deploy:
          name: Push images to the Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make docker-load-image DOCKER_IMAGE_DEPOT=/tmp/workspace
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi

workflows:
  version: 2

  build:
    jobs:
      - alpine-3.6
      - alpine-edge
      - centos-7
      - publish:
          requires:
            - alpine-3.6
            - alpine-edge
            - centos-7
