version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:edge
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.15.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Remote Docker engine version and images
          command: |
            docker --version
            docker-compose --version
            docker image ls
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - run:
          # The latest Dockerspec image must be built first because it will be
          # used to test itself and the subsequent images
          name: sicz/dockerspec:latest
          working_directory: dockerspec
          command: |
            make ci
      - run:
          name: sicz/dockerspec:devel
          working_directory: dockerspec/devel
          command: |
            make ci
      - run:
          name: sicz/baseimage-alpine:latest
          working_directory: alpine
          command: |
            make ci
      - run:
          name: sicz/baseimage-alpine:devel
          working_directory: alpine/devel
          command: |
            make ci
      - run:
          name: sicz/baseimage-centos:latest
          working_directory: centos
          command: |
            make ci
      - run:
          name: sicz/baseimage-centos:devel
          working_directory: centos/devel
          command: |
            make ci
      - deploy:
          name: Push images to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push-all
            fi
