version: 2
jobs:
  build:
    docker:
      - image: sicz/dockerspec@sha256:fcc2eb828bc8ba898af410b46484725e424b9851d580278f5a2c4abdec5e5780
    environment:
      - MAKEFLAGS=--no-print-directory
    steps:
      - checkout
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Remote Docker engine version
          command: |
            docker version
      - run:
          name: Build and test latest Alpine Linux Docker image
          command: |
            make ci-rebuild-and-test DOCKER_TEST_IMAGE=
      - run:
          name: Build and test development Alpine Linux Docker image
          working_directory: devel
          command: |
            make ci-rebuild-and-test DOCKER_TEST_IMAGE=
      - run:
          name: Build and test latest CentOS Docker image
          working_directory: centos
          command: |
            make ci-rebuild-and-test DOCKER_TEST_IMAGE=
      - run:
          name: Build and test development CentOS Docker image
          working_directory: centos/devel
          command: |
            make ci-rebuild-and-test DOCKER_TEST_IMAGE=
      - deploy:
          name: Push latest Alpine Linux Docker image to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
      - deploy:
          name: Push development Alpine Linux Docker image to Docker Hub
          working_directory: devel
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
      - deploy:
          name: Push latest CentOS Docker image to Docker Hub
          working_directory: centos
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
      - deploy:
          name: Push development CentOS Docker image to Docker Hub
          working_directory: centos/devel
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
