################################################################################

BASEIMAGE_TAG		?= edge
DOCKER_TAGS		?=

################################################################################

# Docker Compose file version:
# - docker: 3.3
# - docker-compose: 3.3
# DOCKER_VERSION		?= 17.06.0-ce
# DOCKER_COMPOSE_VERSION	?= 1.15.0
#
RUBY_VERSION			?= 2.4.1-r4
#
# GEM_DOCKER_API_VERSION	?= 1.33.6
# GEM_RSPEC_VERSION		?= 3.6.0
# GEM_SERVERSPEC_VERSION	?= 2.39.1

################################################################################

DOCKER_HOME_DIR		?= ../..
include ../Makefile

################################################################################
